# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_datatypes/custom_types.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "custom_datatypes.custom_types.AnyValue" do
    oneof :kind do
      optional :null_value, :enum, 1, "google.protobuf.NullValue"
      optional :number_value, :double, 2
      optional :string_value, :string, 3
      optional :bool_value, :bool, 4
      optional :struct_value, :message, 5, "google.protobuf.Struct"
      optional :list_value, :message, 6, "custom_datatypes.custom_types.ListAnyValue"
      optional :int_value, :int64, 7
      optional :struct_any_value, :message, 8, "custom_datatypes.custom_types.StructAnyValue"
    end
  end
  add_message "custom_datatypes.custom_types.ListAnyValue" do
    repeated :values, :message, 1, "custom_datatypes.custom_types.AnyValue"
  end
  add_message "custom_datatypes.custom_types.StructAnyValue" do
    map :value, :string, :message, 1, "custom_datatypes.custom_types.AnyValue"
    optional :exclude_value, :bool, 2
  end
  add_message "custom_datatypes.custom_types.DoubleNullValue" do
    oneof :kind do
      optional :value, :double, 1
      optional :null_value, :enum, 2, "google.protobuf.NullValue"
      optional :exclude_value, :bool, 3
    end
  end
  add_message "custom_datatypes.custom_types.FloatNullValue" do
    oneof :kind do
      optional :value, :float, 1
      optional :null_value, :enum, 2, "google.protobuf.NullValue"
      optional :exclude_value, :bool, 3
    end
  end
  add_message "custom_datatypes.custom_types.Int64NullValue" do
    oneof :kind do
      optional :value, :int64, 1
      optional :null_value, :enum, 2, "google.protobuf.NullValue"
      optional :exclude_value, :bool, 3
    end
  end
  add_message "custom_datatypes.custom_types.UInt64NullValue" do
    oneof :kind do
      optional :value, :uint64, 1
      optional :null_value, :enum, 2, "google.protobuf.NullValue"
      optional :exclude_value, :bool, 3
    end
  end
  add_message "custom_datatypes.custom_types.Int32NullValue" do
    oneof :kind do
      optional :value, :int32, 1
      optional :null_value, :enum, 2, "google.protobuf.NullValue"
      optional :exclude_value, :bool, 3
    end
  end
  add_message "custom_datatypes.custom_types.UInt32NullValue" do
    oneof :kind do
      optional :value, :uint32, 1
      optional :null_value, :enum, 2, "google.protobuf.NullValue"
      optional :exclude_value, :bool, 3
    end
  end
  add_message "custom_datatypes.custom_types.BoolNullValue" do
    oneof :kind do
      optional :value, :bool, 1
      optional :null_value, :enum, 2, "google.protobuf.NullValue"
      optional :exclude_value, :bool, 3
    end
  end
  add_message "custom_datatypes.custom_types.StringNullValue" do
    oneof :kind do
      optional :value, :string, 1
      optional :null_value, :enum, 2, "google.protobuf.NullValue"
      optional :exclude_value, :bool, 3
    end
  end
  add_message "custom_datatypes.custom_types.ListStringNullValue" do
    repeated :values, :message, 1, "custom_datatypes.custom_types.StringNullValue"
  end
end

module CustomDatatypes
  module CustomTypes
    AnyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.AnyValue").msgclass
    ListAnyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.ListAnyValue").msgclass
    StructAnyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.StructAnyValue").msgclass
    DoubleNullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.DoubleNullValue").msgclass
    FloatNullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.FloatNullValue").msgclass
    Int64NullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.Int64NullValue").msgclass
    UInt64NullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.UInt64NullValue").msgclass
    Int32NullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.Int32NullValue").msgclass
    UInt32NullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.UInt32NullValue").msgclass
    BoolNullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.BoolNullValue").msgclass
    StringNullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.StringNullValue").msgclass
    ListStringNullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("custom_datatypes.custom_types.ListStringNullValue").msgclass
  end
end
